#!/bin/bash

# So, the idea here is that I have many software projects where I have a scripts folder to do things to the project, at the git root.
# but I don't want to be in some deep folder working, and then have to do like ../../../../scripts/script.sh to run stuff
# For example if I'm in a project and I want to add a new EF migration, and I have a script called add-migration.sh in the project's scripts folder
# I want to be able to do like `run add-migration migrationName`, and be able to run the script with those args
#
# So this does that, it goes up the directory tree looking for scripts folders, and looking for the name you gave it in those folders.
# If it finds something, it'll run it with all of the remaining arguments.
#
# I don't write many bash scripts, so this could probably be done much more nicely and/or better-er..

runScript() {
  echo "-----------"
  echo "running: $1"
  echo "-----------"

  cd "$(dirname $1)"

  /bin/bash "$1" "${@:2}"

  exitCode=$?

  exit $exitCode
}

if [[ $# -lt 1 ]]; then
  echo "Usage: run [script name]"
  exit 1
fi

scriptFoldersToLookFor=(".scripts" "scripts")
extensionsToLookFor=(".sh")
scriptName="$1"
startingDirectory="$(pwd)"
currentDirectory="$startingDirectory"
homeDirectory="$HOME"

while [[ "$currentDirectory" != "$homeDirectory" ]]; do

  for scriptFolder in ${scriptFoldersToLookFor[@]}; do
    scriptsDirectory="$currentDirectory/$scriptFolder"

    if [[ -d "$scriptsDirectory" ]]; then
      scriptLocation="$scriptsDirectory/$scriptName"
      if [[ -f "$scriptLocation" ]]; then
        runScript "$scriptLocation" "${@:2}"
      fi

      for extension in ${extensionsToLookFor[@]}; do
        scriptLocation="$scriptsDirectory/$scriptName$extension"
        if [[ -f "$scriptLocation" ]]; then
          runScript "$scriptLocation" "${@:2}"
        fi
      done
    fi
  done

  currentDirectory="$(dirname "$currentDirectory")"
done


echo "Could not find '$scriptName' in any scripts directory"
exit 2

